### PR TITLE
Add a load type enum field

### PR DESCRIPTION
**Pull request by AlexIIL**
[Rich Diff](https://github.com/QuiltMC/rfcs/pull/30/files?short_path=4f0177c#diff-4f0177c28d2ee6074572764a79131c032c2058b924cf0e25872c2547fed9f736)

In order to support *not* loading modules if they aren't needed I'd like to add a new enum field `load_type` to quilt.mod.json. I should have opened this a while ago, sorry. (This is a port of FabricMC/fabric-loader#342)

### CODE REVIEW

**Comment by AlexIIL** [comment]
I marked this as a draft while I tested an implementation for this - which is done now.

**Comment by i509VCB** [comment]
My guess is plugin infrastructure would have to exist or rely on mods correctly declaring their dependencies to handle the loading?

**Comment by AlexIIL** [comment]
We *could* make plugins handle this, but I think it makes more sense to include this in the base mod defining? it's not very complicated functionality anyway.

**Review by Haven-King — APPROVED** [review]

**Review by TheGlitch76 — APPROVED** [review]

**Comment by TheGlitch76** [comment]
We missed the formal FCP but this PR is a minor change and has sat accepted for two weeks, so we're merging it now.

**Pull request merged**
