### PR TITLE
License the repository under CC-BY-SA 4.0

### PR DESCRIPTION
**Pull request by Akarys42**
This license grants the right to anyone to share and adapt the RFCs, as long as the original text is correctly attributed and the new text is shared under the same license. For more information, please see [the Creative Commons page](https://creativecommons.org/licenses/by-sa/4.0/). 

This license has been voted on by the Quilt Developers. 

Screenshot_20220803-104601

Contributors: if your review has been requested, it means you contributed to this repository and your approval is needed. Please leave a comment with your choice, and approve the PR if you agree with this change.

### CODE REVIEW

**Comment by Akarys42** [comment]
I couldn't request a review from the following people: @i509VCB, @sciwhiz12, @ToffeeMax, @LemmaEOF

**Review by Southpaw1496 — APPROVED** [review]

**Comment by Southpaw1496** [comment]
First

Screenshot 2022-08-03 at 10 11 10 am

**Review by gdude2002 — APPROVED** [review]

**Review by sciwhiz12 — APPROVED** [review]

**Review by i509VCB — APPROVED** [review]
I agree to relicense my contributions to the repository under the CC-BY-SA 4.0 license

**Comment by CheaterCodes** [comment]
Thanks for the copy-pasta.

I agree to relicense my contributions to the repository under the CC-BY-SA 4.0 license

**Review by CheaterCodes — APPROVED** [review]

**Review by TheGlitch76 — APPROVED** [review]

**Review by TibiNonEst — APPROVED** [review]

**Review by SilverAndro — APPROVED** [review]

**Review by OroArmor — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]

**Review by AlexIIL — APPROVED** [review]
I agree to relicense my contributions to the repository under the CC-BY-SA 4.0 license

**Review by Forkk — APPROVED** [review]
I agree to relicense my contributions to the repository under the CC-BY-SA 4.0 license

**Review by LemmaEOF — APPROVED** [review]
Oh, right, I forgot I wrote some of these. I agree to relicense my contributions to the repository under the CC-BY-SA 4.0 license!

**Review by Earthcomputer — APPROVED** [review]

**Comment by ToffeeMax** [comment]
By the power vested in me, by the grace of the minecraft Gods, I approve this license change <3

**Review by ToffeeMax — APPROVED** [review]

**Review by Oliver-makes-code — APPROVED** [review]

**Review by Haven-King — APPROVED** [review]

**Review by mrmangohands — COMMENTED** [review]
I approve the license change 👍

**Comment by wafflecoffee** [comment]
With that, that's everyone accounted for! This can be merged.

**Pull request merged**
