### PR TITLE
RFC #63: Modular Versioning format

### PR DESCRIPTION
**Pull request by LemmaEOF**
[rendered view](https://github.com/LemmaEOF/rfcs/blob/modver/specification/0063-modver.md)

This RFC is still a draft; its intent is stated in the document, and a full formalized specification will be
written when I have the time. Others are welcome to write a BNF or spec for the format and
contribute it to this RFC in the meantime.

### CODE REVIEW

**Comment by LemmaEOF** [comment]
PR withdrawn until it's more complete

**Comment by Gaming32** [comment]
Maybe mark it as draft?

**Comment by LemmaEOF** [comment]
it was.

**Comment by Gaming32** [comment]
Oh

**Pull request closed without merging**
