### PR TITLE
RFC 61: Sponsorship Guidelines

### PR DESCRIPTION
**Pull request by Southpaw1496**
Rendered View: https://github.com/Southpaw1496/rfcs/blob/master/rfc/0061-sponsorships.md

This RFC outlines a procedure for applying for, accepting, running, and terminating any sponsorship that we may receive (e.g 1Password, Starchild Systems etc.). It has guidelines for ideal sponsors to meet, as well as a validation process to gather community feedback on sponsors, and a procedure for addressing concerns that the team or community may have with a given sponsor.

### CODE REVIEW

**Review by Akarys42 — APPROVED** [review]

**Review by ImperatorStorm — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]

**Review by Redblueflame — APPROVED** [review]

**Comment by TwilightFlower** [comment]
The main issue I have with this is the use of the forum exclusively. Even if posts are mirrored to discord, it creates a barrier of creating an account on yet another service in order to express concerns.

**Comment by Southpaw1496** [comment]
The "Rational and Alternatives" section included reasoning for why the forum is most suitable. Namely, it's a place that we control, so people aren't locked out of discussions just because they distrust, have beef with, or otherwise can't access Discord. You can log into the forum using your Discord account, so I don't really see the argument for needing another account. 

Regarding the webhook issue, I think we would create a separate feed for the Sponsorship section, as it is so important, like we currently do with RFCs on Toolchain. Would that resolve that specific issue for you?

**Review by Jamalam360 — COMMENTED** [review]
Maybe mention something about a list of currently active sponsors? A section in the welcome channel? Just something more accessible than digging through the forums.

**Comment by Southpaw1496** [comment]
I was planning to put it on the website, with all our other informational things.

**Review by Jamalam360 — APPROVED** [review]

**Comment by dj-enby** [comment]
Very minor thing, in "Rationale and Alternatives," the third bullet point contains a misspelling, "forgo" should be "forego." Really great document!

**Comment by Southpaw1496** [comment]
Thank you

While spelling mistakes should hardly be considered minor, in this particular instance, the spelling "Forgo" is correct. The Oxford Dictionary lists both spellings as acceptable (and it's not regional), and everything online either says there's no difference, or that "Forgo" means "to leave out" and "Forego" means "to go before", so I don't think this is a mistake.

**Review by autumnblazey — APPROVED** [review]

**Review by Trikzon — APPROVED** [review]

**Review by Lorenzo0310200 — APPROVED** [review]

**Comment by Akarys42** [comment]
This PR has passed RFC and can be merged

**Pull request merged**
